### ISSUE TITLE
Add support for multiple CI configs per one GitHub repo

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#108]
Currently recink assumes one on one relationship between GitHub and CI. Please add support for multiple CI configs.

For example:
```yaml
[...]
  terraform:
    resource-dirname: '.resource'
    use-cache: true
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'

vpc1:
  root: './vpc1'
  ci:
    provider: jenkins
    project: my_vpc1_prj
  terraform:
    vars:
      region: 'us-west-1'
    run-after:
      - vpc2

vpc2:
  root: './vpc2'
  ci:
    provider: travis-ci
    project: my_vpc2_prj
  terraform:
    vars:
      region: 'us-west-1'

ec2:
  root: './ec2'
  ci:
    provider: team-city
    project: my_ec2_prj
  terraform:
    vars:
      region: 'us-west-2'
```
