### ISSUE TITLE
Integrate run unit and run e2e into run terraform

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#110]
It should be as simple as configuring `.recink.yml`, similar to below example:
```yaml
tf_script:
  root: './tf_script'
  terraform:
    version: 0.11.0
    plan: true
    apply: true
    destroy: true
    test:
      mapping: './tests/mapping.json'
      plan: './tests/unit'
      mocha:
         options:
          ui: 'bdd'
          reporter: 'spec'
        
      apply: './tests/e2e'
      testcafe:
      screenshot:
        enabled: true
        take-on-fail: true
        path: './tests/e2e/screenshots'
      browsers:
        - firefox --headless
```

- Add a possibility to configure browser type and mode for e2e execution (e.x. - firefox --headless)
- If it is not defined use the default recink parameters for browser and its mode
