### ISSUE TITLE
Decouple testcafe from recink and move it into new component

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#117]
- framework parameter should be placed under e2e test component
**configuration example** 

```
e2e:
    testcafe:      - framework used for e2e test execution
      screenshot:
        enabled: true
        take-on-fail: true
        path: './tests/e2e/screenshots'
      browsers:
        - firefox --headless
    pattern:
      - /.+\.e2e\.js$/i
    ignore: ~
```
