### ISSUE TITLE
Overwrite tfvar files doesn't work properly

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#120]
I have the following setup:

1) In `.recink.yml`
```yaml
your_tf_script_name:
  root: './your_tf_script_path'
  terraform:
    plan: true
    apply: false
    destroy: false
    var-files:
      - prod.tfvars
      - common1.tfvars
      - common2.tfvars
...
```

2) In CLI
```shell
recink run terraform -vv \
  --tf-varfiles="dev.tfvars,common.tfvars"
```

Expected result: apply values from dev.tfvars and common.tfvars
Actual result: apply values from dev.tfvars, common.tfvars and common2.tfvars
