### ISSUE TITLE
Use mapping json to target tests based on code changes / git diff

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#122]
It should be as simple as configuring `.recink.yml`, similar to below example:

```yaml
tf_script:
  root: './tf_script'
  terraform:
    version: 0.11.0
    plan: true
    apply: true
    destroy: true
    test:
      mapping: './tests/mapping.json'
      plan: './tests/unit/tf_script/'
      apply: './tests/e2e/tf_script/'
```
