### ISSUE TITLE
Add an option to run specified browser type and mode for e2e tests execution   

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#130]
Expected result:
 - Run e2e tests with the specified browser and mode defined under e2e component in .recink.yml 
```e2e:
    pattern:
      - /.+\.e2e\.js$/i
    screenshot:
      enabled: true
      take-on-fail: true
      path: './tests/e2e/screenshots'
    browsers:
      - firefox --headless ```  - in this case Firefox browser is expected to run e2e tests instead of Chromium (which is default for recink)

**Comment by ddimitrioglo** [comment]
@eistrati @avozicov 
from the terraform module we do not have access to the e2e params, how can we workaround this?
```
ec2:
  root: './ec2'
  terraform:
    version: 0.10.0
    plan: false
    apply: false
    destroy: true
    test:
      plan: './ec2/tests/'
      apply: './ec2/tests/'
      browsers:                          <= something like this?
        - firefox --headless        <= something like this?
```

**Comment by eistrati** [comment]
@ddimitrioglo as discussed this morning, we agreed on the following setup:

```yaml
--- 
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    use-cache: false
    save-show-output: tfshow.txt
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
    test:
      plan: './tests/unit/'
      apply: './tests/e2e/'
      unit:
        mocha:
          options:
            ui: 'bdd'
            reporter: 'spec'
      e2e:
        testcafe:
          screenshot:
            enabled: true
            take-on-fail: true
            path: './tests/e2e/screenshots'
          browsers:
            - firefox --headless
  npm:
    scripts: []
    dependencies:
      chai: 'latest'
  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~
  e2e:
    testcafe:
      screenshot:
        enabled: true
        take-on-fail: true
        path: './tests/e2e/screenshots'
      browsers:
        - firefox --headless
    pattern:
      - /.+\.e2e\.js$/i
    ignore: ~

# ec2:
#   root: './ec2'
#   terraform:
#     version: 0.11.0
#     var-files:
#       - workspace.default.tfvars
#     test:
#       plan: './tests/unit/'
#       apply: './tests/e2e/'
#     current-workspace: default
#     available-workspaces:
#       test:
#         plan: true
#         apply: true
#         destroy: true
#         var-files:
#           - workspace.test.tfvars
#       prod:
#         plan: true
#         apply: false
#         destroy: false
#         var-files:
#           - workspace.prod.tfvars

ec2_dev:
  root: './ec2'
  terraform:
    version: 0.11.0
    var-files:
      - workspace.dev.tfvars

ec2_prod:
  root: './ec2'
  terraform:
    version: 0.11.0
    var-files:
      - workspace.prod.tfvars

e2e:
 root: './tests/e2e/'

unit:
 root: './tests/unit/'
```

**Comment by avozicov** [comment]
Test **Passed**
Acceptance Criteria:
- There should be a possibility to define browser type and mode for test component configured under recourse module
- In this case specified browser should be executed instead of the default one and browser mode (--headless) should be also applied if specified 

Configuration example with the specified browser type and mode 
```
rds_restore:
  root: './rds_restore'
  terraform:
    version: 0.11.0
    plan: false
    apply: true
    destroy: false
    test:
      mapping: './tests/mapping.json'
      plan: './tests/unit'
      apply: './tests/e2e'
      e2e:
        testcafe:
          browsers:
            - firefox --headless  
```
