### ISSUE TITLE
Add an option to configure tests components in recink run terraform command

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#131]
**e2e component** should contain 3 levels:
`first level:`
`- framework`     used to perform e2e tests (e.x. `TestCafe`)

`second level under framework option:`
`- screenshot`    used to configure screenshots component
`- browsers`      used to define browser type and mode (e.x. `firefox --headless`)

**unit component** should contain 3 levels:
`first level:`
`- framework`

`second level under framework option:`
`- options`

- It is expected to have a possibility to configure and apply all the listed options for e2e and unit components during execution with recink run terraform command

**Configuration Example**
```
rds_restore:
  root: './rds_restore'
  terraform:
    version: 0.11.0
    plan: false
    apply: false
    destroy: false
    test:
      mapping: './tests/mapping.json'
      plan: './tests/unit'
      mocha:
         options:
          ui: 'bdd'
          reporter: 'spec'
        
      apply: './tests/e2e'
      testcafe:
      screenshot:
        enabled: true
        take-on-fail: true
        path: './tests/e2e/screenshots'
      browsers:
        - firefox --headless
```
