### ISSUE TITLE
Custom resource module does not overrides the default terraform config

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#144]
Please follow the provided steps to reproduce the issues:
- Configure basic terraform script for aws resource
- Configure terraform modules in `recink.yml` in the following mode:

```
terraform:
    resource: '.resource'
    cache: 
      options:
          - 's3://[your_bucket_name]'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
    plan: false
    apply: true
    destroy: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
  
[module_name]:
  root: './module_name'
  terraform:
    version: '0.11.0'
    plan: true
    apply: false
    destroy: false
    current-workspace: default
    available-workspaces:
      prod:
        plan: false
        apply: false
        destroy: false
        var-files:
          - terraform.tfvars
```
- run `recink run terraform` command including required module `--include-modules='[module_name]'`

As we can see from the `.recink.yml` config it is expected to skip `apply` for `[module_name]` and run just `plan` option which is overridden for default `terraform` config in `[module_name]` section 

Issue:
- Apply is not skipped after running `recink run terraform --include-moduels='[module_name]'` as was defined in the particular module in `.recink.yml`

Please refer to attachment for more details:
![apply.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/89d25bc1-f6d1-4b09-8d33-05b360f5b618)

**Comment by avozicov** [comment]
Test **Passed**
Acceptance Criteria
- [plan, apply, destroy] options should be overridden in global terraform config if they was defined  in custom modules config 

for example:
```
 terraform:
    resource: '.resource'
    cache: 
      options:
          - 's3://[your_bucket_name]'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
    plan: false
    apply: false
    destroy: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
[custom_module_name]:
  root: './[custom_module_name]'
  terraform:
    version: '0.11.0'
    plan: true
    apply: false
    destroy: false
```

- In this case we expect for plan not to be skipped because it was defined in custom module config

Please refer to attachment for more details:
<img width="563" alt="screen_shot_2018-02-28_at_17_34_37" src="https://user-images.githubusercontent.com/12330493/36796306-eee44402-1cad-11e8-93df-d7fba96f9439.png">
