### ISSUE TITLE
Wrong behavior for e2e tests execution when using default `.recink.yml` template

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#150]
Please follow the provided steps to reproduce the issue:
- run `npm install -g recink`
- `mkdir ~/test`
- `cd ~/test`
- `mkdir scripts`
- create e2e test with the following name `qa-test.e2e.js`and place it in scripts directory 
- run `recink configure recink` to generate basic .recink.yml template
- uncomment everything related to e2e component in `.recink.yml` and define root for e2e module 

.recink.yml example:
```
--- 
$:
  npm:
    dependencies:
      chai: 'latest'
  emit:
    # Files to include
    pattern:
      - /.+\.js$/i
    # Files to exclude
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  e2e:
    reporter: ~
    pattern:
      - /.+\.e2e\.js$/i
    ignore: ~
    screenshot:
      enabled: false                  
      path: 'path/to/screenshots'
      take-on-fail: false
    browsers:
      - chrome

e2e:
  root: './scripts/'
``` 

e2e script example from lovely TestCafe framework ;)
```
import { Selector } from 'testcafe';

fixture `My fixture`
    .page `http://devexpress.github.io/testcafe/example/`;

test('Assertion with Selector', async t => {
    const developerNameInput = Selector('#developer-name');

    await t
        .expect(developerNameInput.innerText).eql('')
        .typeText(developerNameInput, 'Peter')
        .expect(developerNameInput.innerText).eql('Peter');
});
```

Issue:
- when running `recink run e2e` command with uncommented `reporter:~` option all e2e scripts are skipped and not executed 

Please refer to attachment for more details:
![Screen Shot 2018-03-01 at 16.14.33.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/d5a00da5-5519-44a8-b4a4-ae86df5d7fe8)
