### ISSUE TITLE
Workspace options does not override custom and global module config 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#155]
We should fix the behavior of overriding global and custom module options by the those defined in `workspace` config 

For example:
- it is expected for `plan` option to be applied if it defined in config as follows:
```
[your_module_name]:
  root: './[your_module_name]'
  terraform:
    version: '0.11.0'
    plan: false      - this option is expected to be overridden by `prod workspace` config
    apply: false 
    destroy: false
    current-workspace: default
    available-workspaces:
      prod:
        plan: true    - this option should override the custom module config
        apply: false
        destroy: false
        var-files:
          - terraform.tfvars
```

Actual Result:
- If we use the provided .recink.yml example the plan option is being skipped which is not expected  

Note: 
- to reproduce the issue run `recink run terraform` with `--tf-workspace='[your_workspace_env]'`

Please refer to attachment for more details: 
![plan skipped.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/38571894-9ee3-4fde-a6f3-7ddde8eae24d)
