### ISSUE TITLE
Skip option for `plan` is not applied 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#156]
We need to fix output for the use case when running `recink run terraform` with `plan : false` option 

Actual Result:
   - when `plan` options is set to `false` we still getting the output containing plan information for the particular resource 

Please use the following config and provided command to reproduce the issue:
- run `recink run terraform` command using the following config in `.recink.yml`
```
---
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
    '$.terraform.cache.options.1.region': 'eval'
    '$.terraform.cache.options.1.accessKeyId': 'eval'
    '$.terraform.cache.options.1.secretAccessKey': 'eval'
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    cache: 
      options:
          - 's3://[your_bucket_name'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
    plan: false
    apply: false
    destroy: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
qa-resource:
  root: './qa-resource'
  terraform:
    version: 0.11.0
    var-files:
      - qa.tfvars 
```

Please refer to attachment for output log:
![Screen Shot 2018-03-06 at 15.18.46.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/a47a02e5-ce1a-40db-ba42-a23773e8b5b1)

**Comment by ddimitrioglo** [comment]
@avozicov could not reproduce the issue with the following config

```yml
--- 
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    plan: false
    apply: false
    destroy: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'

iam2:
  root: './iam'
  terraform:
    cache: false
```

Pease let me know if I'm missing something
