### ISSUE TITLE
Global resource config does not override custom module options

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#157]
We need to fix the behavior for defining and applying global resource configuration 
Actual Result:
- Case when `plan, apply, destroy` options are set to `true` in global terraform config they are not applied to custom modules configuration 

Please use the following config and commands to reproduce the issue:
- apply a resource with the name `qa-resource`
- run `recink run terraform` with `destroy` option set to `true`
```
---
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
    '$.terraform.cache.options.1.region': 'eval'
    '$.terraform.cache.options.1.accessKeyId': 'eval'
    '$.terraform.cache.options.1.secretAccessKey': 'eval'
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    cache: 
      options:
          - 's3://[your_bucket_name]'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
    plan: false
    apply: false
    destroy: true
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
qa-resource:
  root: './qa-resource'
  terraform:
    version: 0.11.0
    var-files:
      - qa.tfvars 
```
Please refer to attachment for more details:
![Screen Shot 2018-03-06 at 16.29.38.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/24c4af25-4d9a-4d12-bab0-0c31f3b82a8c)

**Comment by ddimitrioglo** [comment]
@avozicov could not reproduce with the following config:

```yml
---
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    plan: false
    apply: false
    destroy: true
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'

iam2:
  root: './iam'
  terraform:
    cache: false
```

Please let me know if I'm missing something
