### ISSUE TITLE
Improve default `.recink.yml` by adding `cache:false` option under terraform module

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#167]
I would suggest to add `cache:false` option into default `.recink.yml` file under terraform module.
Here is the use-case:
- Try to configure and deploy an instance from the example bellow https://www.terraform.io/intro/getting-started/build.html 
(which does not required cache option)
- Run `recink configure recink` command to generate the default `.recink.yml`
- Use the following `.recink.yml` config (which suppose to be basic for the module above)
```
---
$:
  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    plan: true
    apply: false
    destroy: false
qa:
  root: './'
```
- Then run `recink run terraform` command 

As a result you will get the following error until you add `cache: false` under `terraform component` in `.recink.yml`
![Screen Shot 2018-04-11 at 16.55.27.png](https://images.zenhubusercontent.com/55a909194f7a08fbb7f3c7e0/f9e1079d-6930-420f-9b21-af42b33f4e0e)
