### ISSUE TITLE
Error for uploading data by `recink cnci` component

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/recink#191]
I am facing issue when trying to upload terraform plan data using `recink run terraform -c cnci` command 

To reproduce the issue please follow this steps:
- Configure basic terraform script https://www.terraform.io/intro/getting-started/build.html
- Create CNCI account by calling `https://api.terrahub.io/v1/cnci/account/create` endpoint and retrieve cnci-token 
- Configure `.recink.yml` file and define terraform module root and expected execution scenario for terraform script 
- Run `recink run terraform -c cnci` and provide valid cnci-token 
```
--- 
$:
  emit: ~
  preprocess:
    '$.cnci.token': 'eval'
  terraform:
    version: '0.11.0' 
    cache: false
    init: true
    plan: true
    apply: false
    destroy: false                                                      
  cnci:
    token: process.env.CNCI_TOKEN
you_tf_module:
  root: './you_tf_module/'
```

Expected result:
- It is expected to upload parsed terraform plan data in the defined s3 bucket (shared privately) when running `recink run terraform` with `-c cnci` option

Actual result:
- Plan data is available in cli but is not uploaded in the expected s3 bucket

 Note:
- the same issue is reproduced for `build log and metadata` use case
