### ISSUE TITLE
Add support for 3'rd party cache files using cache component

### ISSUE THREAD

**Issue by AlexanderC** [MitocGroup/recink#46]
Add support for 3'rd party cache files using cache component.

Sample configuration:

```
cache:
    driver: 's3'
    options:
      - 's3://travis-metadata/cache/MitocGroup/atm'
      -
        region: 'process.env.AWS_DEFAULT_REGION'
        accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
        secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'
    assets: # new configuration goes here!
        - sample.cache.json
```
