### ISSUE TITLE
Enable automatic parsing of extra variables in terraform component

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/recink#81]
Reference: https://www.terraform.io/intro/getting-started/variables.html#from-a-file

Example:
```yaml
ec2_rds:
  root: './ec2_rds'
  terraform:
    vars:
      region: 'us-west-2'
    var-files:
      - './secret.tfvars'
      - './production.tfvars'
```
